;;; gcode-mode-eldoc.el --- G-Code documentation entries  -*- lexical-binding: t -*-

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; This file has been bootstrapped by reading descriptions
;; from the RepRap Wiki:
;;
;; https://reprap.org/mediawiki/index.php?title=G-code
;;
;; See "bootstrap-doc.sh" for the *rough* script used to extract the
;; basic descriptions. The resulting entries were then hand-edited.

;;; Code:

(defun gcode-mode--doc-build ()
  "Generate G-Code documentation entries"
  (let ((hash (make-hash-table :test 'equal)))
    (puthash "G0" "Move" hash)
    (puthash "G1" "Move" hash)
    (puthash "G2" "Controlled Arc Move" hash)
    (puthash "G3" "Controlled Arc Move" hash)
    (puthash "G4" "Dwell" hash)
    (puthash "G6" "Direct Stepper Move" hash)
    (puthash "G10" "Set tool Offset and/or workplace coordinates and/or tool temperatures" hash)
    (puthash "G10" "Retract" hash)
    (puthash "G11" "Unretract" hash)
    (puthash "G12" "Clean Tool" hash)
    (puthash "G17" "Plane Selection (CNC specific)" hash)
    (puthash "G18" "Plane Selection (CNC specific)" hash)
    (puthash "G19" "Plane Selection (CNC specific)" hash)
    (puthash "G20" "Set Units to Inches" hash)
    (puthash "G21" "Set Units to Millimeters" hash)
    (puthash "G22" "Firmware Retract" hash)
    (puthash "G23" "Firmware Recover" hash)
    (puthash "G26" "Mesh Validation Pattern" hash)
    (puthash "G28" "Move to Origin (Home)" hash)
    (puthash "G29" "Detailed Z-Probe" hash)
    (puthash "G29.1" "Set Z probe head offset" hash)
    (puthash "G29.2" "Set Z probe head offset calculated from toolhead position" hash)
    (puthash "G30" "Single Z-Probe" hash)
    (puthash "G31" "Set or Report Current Probe status" hash)
    (puthash "G31" "Dock Z Probe sled" hash)
    (puthash "G32" "Probe Z and calculate Z plane" hash)
    (puthash "G32" "Undock Z Probe sled" hash)
    (puthash "G33" "Firmware dependent" hash)
    (puthash "G33" "Measure/List/Adjust Distortion Matrix (Repetier - Redeem)" hash)
    (puthash "G34" "Z Stepper Auto-Align" hash)
    (puthash "G34" "Calculate Delta Height from toolhead position (DELTA)" hash)
    (puthash "G40" "Compensation Off (CNC specific)" hash)
    (puthash "G42" "Move to Grid Point" hash)
    (puthash "G53" "Coordinate System Select (CNC specific)" hash)
    (puthash "G54" "Coordinate System Select (CNC specific)" hash)
    (puthash "G55" "Coordinate System Select (CNC specific)" hash)
    (puthash "G56" "Coordinate System Select (CNC specific)" hash)
    (puthash "G57" "Coordinate System Select (CNC specific)" hash)
    (puthash "G58" "Coordinate System Select (CNC specific)" hash)
    (puthash "G59" "Coordinate System Select (CNC specific)" hash)
    (puthash "G60" "save current position to slot" hash)
    (puthash "G61" "Apply/restore saved coordinates to the active extruder." hash)
    (puthash "G75" "Print temperature interpolation" hash)
    (puthash "G76" "PINDA probe temperature calibration" hash)
    (puthash "G80" "Cancel Canned Cycle (CNC specific)" hash)
    (puthash "G80" "Mesh-based Z probe" hash)
    (puthash "G81" "Mesh bed leveling status" hash)
    (puthash "G82" "Single Z probe at current location" hash)
    (puthash "G83" "Babystep in Z and store to EEPROM" hash)
    (puthash "G84" "UNDO Babystep Z (move Z axis back)" hash)
    (puthash "G85" "Pick best babystep" hash)
    (puthash "G86" "Disable babystep correction after home" hash)
    (puthash "G87" "Enable babystep correction after home" hash)
    (puthash "G88" "Reserved" hash)
    (puthash "G90" "Set to Absolute Positioning" hash)
    (puthash "G91" "Set to Relative Positioning" hash)
    (puthash "G92" "Set Position" hash)
    (puthash "G92.1" "Reset Coordinate System Offsets (CNC specific)" hash)
    (puthash "G92.2" "Reset Coordinate System Offsets (CNC specific)" hash)
    (puthash "G93" "Feed Rate Mode (Inverse Time Mode) (CNC specific)" hash)
    (puthash "G94" "Feed Rate Mode (Units per Minute) (CNC specific)" hash)
    (puthash "G98" "Activate farm mode" hash)
    (puthash "G99" "Deactivate farm mode" hash)
    (puthash "G100" "Calibrate floor or rod radius" hash)
    (puthash "G130" "Set digital potentiometer value" hash)
    (puthash "G131" "Remove offset" hash)
    (puthash "G132" "Calibrate endstop offsets" hash)
    (puthash "G133" "Measure steps to top" hash)
    (puthash "G161" "Home axes to minimum" hash)
    (puthash "G162" "Home axes to maximum" hash)
    (puthash "G425" "Perform auto-calibration with calibration cube" hash)
    (puthash "M0" "Stop or Unconditional stop" hash)
    (puthash "M1" "Sleep or Conditional stop" hash)
    (puthash "M2" "Program End" hash)
    (puthash "M3" "Spindle On, Clockwise  (CNC specific)" hash)
    (puthash "M4" "Spindle On, Counter-Clockwise (CNC specific)" hash)
    (puthash "M5" "Spindle Off (CNC specific)" hash)
    (puthash "M6" "Tool change" hash)
    (puthash "M7" "Mist Coolant On (CNC specific)" hash)
    (puthash "M8" "Flood Coolant On (CNC specific)" hash)
    (puthash "M9" "Coolant Off (CNC specific)" hash)
    (puthash "M10" "Vacuum On (CNC specific)" hash)
    (puthash "M11" "Vacuum Off (CNC specific)" hash)
    (puthash "M13" "Spindle on (clockwise rotation) and coolant on (flood)" hash)
    (puthash "M16" "Expected Printer Check" hash)
    (puthash "M17" "Enable/Power all stepper motors" hash)
    (puthash "M18" "Disable all stepper motors" hash)
    (puthash "M20" "List SD card" hash)
    (puthash "M21" "Initialize SD card" hash)
    (puthash "M22" "Release SD card" hash)
    (puthash "M23" "Select SD file" hash)
    (puthash "M24" "Start/resume SD print" hash)
    (puthash "M25" "Pause SD print" hash)
    (puthash "M26" "Set SD position" hash)
    (puthash "M27" "Report SD print status" hash)
    (puthash "M28" "Begin write to SD card" hash)
    (puthash "M29" "Stop writing to SD card" hash)
    (puthash "M30" "Delete a file on the SD card" hash)
    (puthash "M30" " Program Stop" hash)
    (puthash "M31" "Output time since last <code>M109</code> or SD card start to serial" hash)
    (puthash "M32" "Select file and start SD print" hash)
    (puthash "M33" "Get the long name for an SD card file or folder" hash)
    (puthash "M33" "Stop and Close File and save restart.gcode" hash)
    (puthash "M34" "Set SD file sorting options" hash)
    (puthash "M35" "Upload firmware NEXTION from SD" hash)
    (puthash "M36" "Return file information" hash)
    (puthash "M37" "Simulation mode" hash)
    (puthash "M40" "Eject" hash)
    (puthash "M41" "Loop" hash)
    (puthash "M42" "Switch I/O pin" hash)
    (puthash "M43" "Stand by on material exhausted" hash)
    (puthash "M43" "Pin report and debug" hash)
    (puthash "M44" "Codes debug - report codes available" hash)
    (puthash "M44" "Reset the bed skew and offset calibration" hash)
    (puthash "M45" "Bed skew and offset with manual Z up" hash)
    (puthash "M46" "Show the assigned IP address" hash)
    (puthash "M47" "Show end stops dialog on the display" hash)
    (puthash "M48" "Measure Z-Probe repeatability" hash)
    (puthash "M49" "Set G26 debug flag" hash)
    (puthash "M70" "Display message" hash)
    (puthash "M72" "Play a tone or song" hash)
    (puthash "M73" "Set/Get build percentage" hash)
    (puthash "M75" "Start the print job timer" hash)
    (puthash "M76" "Pause the print job timer" hash)
    (puthash "M77" "Stop the print job timer" hash)
    (puthash "M78" "Show statistical information about the print jobs" hash)
    (puthash "M80" "ATX Power On" hash)
    (puthash "M81" "ATX Power Off" hash)
    (puthash "M82" "Set extruder to absolute mode" hash)
    (puthash "M83" "Set extruder to relative mode" hash)
    (puthash "M84" "Stop idle hold" hash)
    (puthash "M85" "Set Inactivity Shutdown Timer" hash)
    (puthash "M86" "Set Safety Timer expiration time" hash)
    (puthash "M92" "Set axis_steps_per_unit" hash)
    (puthash "M93" "Send axis_steps_per_unit" hash)
    (puthash "M98" "Call Macro/Subprogram" hash)
    (puthash "M99" "Return from Macro/Subprogram" hash)
    (puthash "M101" "Turn extruder 1 on (Forward), Undo Retraction" hash)
    (puthash "M102" "Turn extruder 1 on (Reverse)" hash)
    (puthash "M103" "Turn all extruders off, Extruder Retraction" hash)
    (puthash "M104" "Set Extruder Temperature" hash)
    (puthash "M105" "Get Extruder Temperature" hash)
    (puthash "M106" "Fan On" hash)
    (puthash "M107" "Fan Off" hash)
    (puthash "M108" "Cancel Heating" hash)
    (puthash "M108" "Set Extruder Speed (BFB)" hash)
    (puthash "M109" "Set Extruder Temperature and Wait" hash)
    (puthash "M110" "Set Current Line Number" hash)
    (puthash "M111" "Set Debug Level" hash)
    (puthash "M112" "Full (Emergency) Stop" hash)
    (puthash "M113" "Set Extruder PWM" hash)
    (puthash "M113" "Host Keepalive" hash)
    (puthash "M114" "Get Current Position" hash)
    (puthash "M115" "Get Firmware Version and Capabilities" hash)
    (puthash "M116" "Wait" hash)
    (puthash "M117" "Get Zero Position" hash)
    (puthash "M117" "Display Message" hash)
    (puthash "M118" "Echo message on host" hash)
    (puthash "M118" "Negotiate Features" hash)
    (puthash "M119" "Get Endstop Status" hash)
    (puthash "M120" "Push" hash)
    (puthash "M121" "Pop" hash)
    (puthash "M120" "Enable endstop detection" hash)
    (puthash "M121" "Disable endstop detection" hash)
    (puthash "M122" "Firmware dependent" hash)
    (puthash "M122" "Diagnose (RepRapFirmware)" hash)
    (puthash "M122" "Set Software Endstop (MK4duo)" hash)
    (puthash "M122" "Debug L6470 drivers (Marlin)" hash)
    (puthash "M123" "Firmware dependent" hash)
    (puthash "M123" "Tachometer value (RepRap)" hash)
    (puthash "M123" "Endstop Logic (MK4duo)" hash)
    (puthash "M124" "Firmware dependent" hash)
    (puthash "M124" "Immediate motor stop" hash)
    (puthash "M124" "Set Endstop Pullup" hash)
    (puthash "M126" "Open Valve" hash)
    (puthash "M127" "Close Valve" hash)
    (puthash "M128" "Extruder Pressure PWM" hash)
    (puthash "M129" "Extruder pressure off" hash)
    (puthash "M130" "Set PID P value" hash)
    (puthash "M131" "Set PID I value" hash)
    (puthash "M132" "Set PID D value" hash)
    (puthash "M133" "Set PID I limit value" hash)
    (puthash "M134" "Write PID values to EEPROM" hash)
    (puthash "M135" "Set PID sample interval" hash)
    (puthash "M136" "Print PID settings to host" hash)
    (puthash "M140" "Set Bed Temperature (Fast)" hash)
    (puthash "M141" "Set Chamber Temperature (Fast)" hash)
    (puthash "M142" "Firmware dependent" hash)
    (puthash "M142" "Holding Pressure" hash)
    (puthash "M142" "Set Cooler Temperature (Fast)" hash)
    (puthash "M144" "Bed Standby" hash)
    (puthash "M146" "Set Chamber Humidity" hash)
    (puthash "M190" "Wait for bed temperature to reach target temp" hash)
    (puthash "M191" "Wait for chamber temperature to reach target temp" hash)
    (puthash "M192" "Wait for Probe Temperature" hash)
    (puthash "M200" "Set filament diameter" hash)
    (puthash "M201" "Set max acceleration" hash)
    (puthash "M202" "Set max travel acceleration" hash)
    (puthash "M203" "Set maximum feedrate" hash)
    (puthash "M204" "Set default acceleration" hash)
    (puthash "M205" "Advanced settings" hash)
    (puthash "M205" "EEPROM Report" hash)
    (puthash "M206" "Offset axes" hash)
    (puthash "M206" "Set EEPROM value" hash)
    (puthash "M207" "Firmware dependent" hash)
    (puthash "M207" "Set retract length" hash)
    (puthash "M207" "Calibrate Z axis with Z max endstop" hash)
    (puthash "M207" "Set jerk without saving to EEPROM" hash)
    (puthash "M208" "Set axis max travel" hash)
    (puthash "M208" "Set unretract length" hash)
    (puthash "M209" "Enable automatic retract" hash)
    (puthash "M210" "Set homing feedrates" hash)
    (puthash "M211" "Disable/Enable software endstops" hash)
    (puthash "M212" "Set Bed Level Sensor Offset" hash)
    (puthash "M217" "Toolchange Parameters" hash)
    (puthash "M218" "Set Hotend Offset" hash)
    (puthash "M220" "Set speed factor override percentage" hash)
    (puthash "M221" "Set extrude factor override percentage" hash)
    (puthash "M220" "Turn off AUX V1.0.5" hash)
    (puthash "M221" "Turn on AUX V1.0.5" hash)
    (puthash "M222" "Set speed of fast XY moves" hash)
    (puthash "M223" "Set speed of fast Z moves" hash)
    (puthash "M224" "Enable extruder during fast moves" hash)
    (puthash "M225" "Disable on extruder during fast moves" hash)
    (puthash "M226" "G-code Initiated Pause" hash)
    (puthash "M226" "Wait for pin state" hash)
    (puthash "M227" "Enable Automatic Reverse and Prime" hash)
    (puthash "M228" "Disable Automatic Reverse and Prime" hash)
    (puthash "M229" "Enable Automatic Reverse and Prime" hash)
    (puthash "M230" "Disable / Enable Wait for Temperature Change" hash)
    (puthash "M231" "Set OPS parameter" hash)
    (puthash "M232" "Read and reset max. advance values" hash)
    (puthash "M240" "Trigger camera" hash)
    (puthash "M240" "Start conveyor belt motor / Echo off" hash)
    (puthash "M241" "Stop conveyor belt motor / echo on" hash)
    (puthash "M245" "Start cooler" hash)
    (puthash "M246" "Stop cooler" hash)
    (puthash "M250" "Set LCD contrast" hash)
    (puthash "M251" "Measure Z steps from homing stop (Delta printers)" hash)
    (puthash "M260" "i2c Send Data" hash)
    (puthash "M261" "i2c Request Data" hash)
    (puthash "M280" "Set servo position" hash)
    (puthash "M290" "Babystepping" hash)
    (puthash "M291" "Display message and optionally wait for response" hash)
    (puthash "M292" "Acknowledge message" hash)
    (puthash "M300" "Play beep sound" hash)
    (puthash "M301" "Set PID parameters" hash)
    (puthash "M302" "Allow cold extrudes" hash)
    (puthash "M303" "Run PID tuning" hash)
    (puthash "M304" "Set PID parameters - Bed" hash)
    (puthash "M305" "Set thermistor and ADC parameters" hash)
    (puthash "M306" "Set home offset calculated from toolhead position" hash)
    (puthash "M307" "Set or report heating process parameters" hash)
    (puthash "M308" "Set or report sensor parameters" hash)
    (puthash "M320" "Activate autolevel (Repetier)" hash)
    (puthash "M321" "Deactivate autolevel (Repetier)" hash)
    (puthash "M322" "Reset autolevel matrix (Repetier)" hash)
    (puthash "M323" "Distortion correction on/off (Repetier)" hash)
    (puthash "M340" "Control the servos" hash)
    (puthash "M350" "Set microstepping mode" hash)
    (puthash "M351" "Toggle MS1 MS2 pins directly" hash)
    (puthash "M355" "Turn case lights on/off" hash)
    (puthash "M360" "Report firmware configuration" hash)
    (puthash "M360" "Move to Theta 0 degree position" hash)
    (puthash "M361" "Move to Theta 90 degree position" hash)
    (puthash "M362" "Move to Psi 0 degree position" hash)
    (puthash "M363" "Move to Psi 90 degree position" hash)
    (puthash "M364" "Move to Psi + Theta 90 degree position" hash)
    (puthash "M365" "SCARA scaling factor" hash)
    (puthash "M366" "SCARA convert trim" hash)
    (puthash "M370" "Morgan manual bed level - clear map" hash)
    (puthash "M371" "Move to next calibration position" hash)
    (puthash "M372" "Record calibration value, and move to next position" hash)
    (puthash "M373" "End bed level calibration mode" hash)
    (puthash "M374" "Save calibration grid" hash)
    (puthash "M375" "Display matrix / Load Matrix" hash)
    (puthash "M376" "Set bed compensation taper" hash)
    (puthash "M380" "Activate solenoid" hash)
    (puthash "M381" "Disable all solenoids" hash)
    (puthash "M400" "Wait for current moves to finish" hash)
    (puthash "M401" "Lower z-probe" hash)
    (puthash "M402" "Raise z-probe" hash)
    (puthash "M403" "Set filament type (material) for particular extruder and notify the MMU" hash)
    (puthash "M404" "Filament width and nozzle diameter" hash)
    (puthash "M405" "Filament Sensor on" hash)
    (puthash "M406" "Filament Sensor off" hash)
    (puthash "M407" "Display filament diameter" hash)
    (puthash "M408" "Report JSON-style response" hash)
    (puthash "M409" "Query object model" hash)
    (puthash "M410" "Quick-Stop" hash)
    (puthash "M412" "Disable Filament Runout Detection" hash)
    (puthash "M413" "Power-Loss Recovery" hash)
    (puthash "M415" "Host Rescue" hash)
    (puthash "M416" "Power loss " hash)
    (puthash "M420" "Set RGB Colors as PWM (MachineKit)" hash)
    (puthash "M420" "Leveling On/Off/Fade (Marlin)" hash)
    (puthash "M421" "Set a Mesh Bed Leveling Z coordinate" hash)
    (puthash "M425" "Backlash Correction" hash)
    (puthash "M450" "Report Printer Mode" hash)
    (puthash "M451" "Select FFF Printer Mode" hash)
    (puthash "M452" "Select Laser Printer Mode" hash)
    (puthash "M453" "Select CNC Printer Mode" hash)
    (puthash "M460" "Define temperature range for thermistor-controlled fan" hash)
    (puthash "M470" "Create Directory on SD-Card" hash)
    (puthash "M471" "Rename File/Directory on SD-Card" hash)
    (puthash "M486" "Cancel Object" hash)
    (puthash "M500" "Store parameters in non-volatile storage" hash)
    (puthash "M501" "Read parameters from EEPROM" hash)
    (puthash "M502" "Restore Default Settings" hash)
    (puthash "M503" "Report Current Settings" hash)
    (puthash "M504" "Validate EEPROM" hash)
    (puthash "M505" "Firmware dependent" hash)
    (puthash "M505" "Clear EEPROM and RESET Printer" hash)
    (puthash "M505" "Set configuration file folder" hash)
    (puthash "M509" "Force language selection" hash)
    (puthash "M524" "Abort SD Printing" hash)
    (puthash "M530" "Enable printing mode" hash)
    (puthash "M531" "Set print name" hash)
    (puthash "M532" "Set print progress" hash)
    (puthash "M540" "Enable/Disable \"Stop SD Print on Endstop Hit\"" hash)
    (puthash "M550" "Set Name" hash)
    (puthash "M551" "Set Password" hash)
    (puthash "M552" "Set IP address, enable/disable network interface" hash)
    (puthash "M553" "Set Netmask" hash)
    (puthash "M554" "Set Gateway" hash)
    (puthash "M555" "Set compatibility" hash)
    (puthash "M556" "Axis compensation" hash)
    (puthash "M557" "Set Z probe point or define probing grid" hash)
    (puthash "M558" "Set Z probe type" hash)
    (puthash "M559" "Upload configuration file" hash)
    (puthash "M560" "Upload web page file" hash)
    (puthash "M561" "Set Identity Transform" hash)
    (puthash "M562" "Reset temperature fault" hash)
    (puthash "M563" "Define or remove a tool" hash)
    (puthash "M564" "Limit axes" hash)
    (puthash "M565" "Set Z probe offset" hash)
    (puthash "M566" "Set allowable instantaneous speed change" hash)
    (puthash "M567" "Set tool mix ratios" hash)
    (puthash "M568" "Turn off/on tool mix ratios (obsolete)" hash)
    (puthash "M569" "Stepper driver control" hash)
    (puthash "M569.1" "Stepper driver closed loop control" hash)
    (puthash "M570" "Configure heater fault detection" hash)
    (puthash "M571" "Set output on extrude" hash)
    (puthash "M572" "Set or report extruder pressure advance" hash)
    (puthash "M573" "Report heater PWM" hash)
    (puthash "M574" "Set endstop configuration" hash)
    (puthash "M575" "Set serial comms parameters" hash)
    (puthash "M577" "Wait until endstop is triggered" hash)
    (puthash "M578" "Fire inkjet bits" hash)
    (puthash "M579" "Scale Cartesian axes" hash)
    (puthash "M580" "Select Roland" hash)
    (puthash "M581" "Configure external trigger" hash)
    (puthash "M582" "Check external trigger" hash)
    (puthash "M584" "Set drive mapping" hash)
    (puthash "M585" "Probe Tool" hash)
    (puthash "M586" "Configure network protocols" hash)
    (puthash "M587" "Store WiFi host network in list, or list stored networks" hash)
    (puthash "M588" "Forget WiFi host network" hash)
    (puthash "M589" "Configure access point parameters" hash)
    (puthash "M590" "Report current tool type and index" hash)
    (puthash "M591" "Configure filament monitoring" hash)
    (puthash "M592" "Configure nonlinear extrusion" hash)
    (puthash "M593" "Configure Dynamic Acceleration Adjustment" hash)
    (puthash "M594" "Enter/Leave Height Following mode" hash)
    (puthash "M600" "Set line cross section" hash)
    (puthash "M600" "Filament change pause" hash)
    (puthash "M601" "Pause print" hash)
    (puthash "M602" "Resume print" hash)
    (puthash "M603" "Stop print" hash)
    (puthash "M605" "Set dual x-carriage movement mode" hash)
    (puthash "M650" "Set peel move parameters" hash)
    (puthash "M651" "execute peel move" hash)
    (puthash "M665" "Set delta configuration" hash)
    (puthash "M666" "Set delta endstop adjustment" hash)
    (puthash "M667" "Select CoreXY mode" hash)
    (puthash "M668" "Set Z-offset compensations polynomial" hash)
    (puthash "M669" "Set kinematics type and kinematics parameters" hash)
    (puthash "M670" "Set IO port bit mapping" hash)
    (puthash "M671" "Define positions of Z leadscrews or bed leveling screws" hash)
    (puthash "M672" "Program Z probe" hash)
    (puthash "M673" "Align plane on rotary axis" hash)
    (puthash "M674" "Set Z to center point" hash)
    (puthash "M675" "Find center of cavity" hash)
    (puthash "M700" "Level plate" hash)
    (puthash "M701" "Load filament" hash)
    (puthash "M702" "Unload filament" hash)
    (puthash "M703" "Configure Filament" hash)
    (puthash "M710" "Firmware dependent" hash)
    (puthash "M710" "Controller Fan settings" hash)
    (puthash "M710" "Erase the EEPROM and reset the board" hash)
    (puthash "M750" "Enable 3D scanner extension" hash)
    (puthash "M751" "Register 3D scanner extension over USB" hash)
    (puthash "M752" "Start 3D scan" hash)
    (puthash "M753" "Cancel current 3D scanner action" hash)
    (puthash "M754" "Calibrate 3D scanner" hash)
    (puthash "M755" "Set alignment mode for 3D scanner" hash)
    (puthash "M756" "Shutdown 3D scanner" hash)
    (puthash "M800" "Fire start print procedure" hash)
    (puthash "M801" "Fire end print procedure" hash)
    (puthash "M851" "Set Z-Probe Offset" hash)
    (puthash "M862" "Print checking" hash)
    (puthash "M862.1" "Check nozzle diameter" hash)
    (puthash "M862.2" "Check model code" hash)
    (puthash "M862.3" "Model name" hash)
    (puthash "M862.4" "Firmware version" hash)
    (puthash "M862.5" "Gcode level" hash)
    (puthash "M871" "PTC Configuration" hash)
    (puthash "M876" "Dialog handling" hash)
    (puthash "M905" "Set local date and time" hash)
    (puthash "M906" "Set motor currents" hash)
    (puthash "M907" "Set digital trimpot motor" hash)
    (puthash "M908" "Control digital trimpot directly" hash)
    (puthash "M909" "Set microstepping" hash)
    (puthash "M910" "Set decay mode" hash)
    (puthash "M910" "TMC2130 init" hash)
    (puthash "M911" "Configure auto save on loss of power (\"power panic\")" hash)
    (puthash "M911" "Set TMC2130 holding currents" hash)
    (puthash "M912" "Set electronics temperature monitor adjustment" hash)
    (puthash "M912" "Set TMC2130 running currents" hash)
    (puthash "M913" "Set motor percentage of normal current" hash)
    (puthash "M913" "Print TMC2130 currents" hash)
    (puthash "M914" "Set/Get Expansion Voltage Level Translator" hash)
    (puthash "M914" "Set TMC2130 normal mode" hash)
    (puthash "M915" "Configure motor stall detection" hash)
    (puthash "M915" "Set TMC2130 silent mode" hash)
    (puthash "M916" "Resume print after power failure" hash)
    (puthash "M916" "Set TMC2130 Stallguard sensitivity threshold" hash)
    (puthash "M917" "Set motor standstill current reduction" hash)
    (puthash "M917" "Set TMC2130 PWM amplitude offset (pwm_ampl)" hash)
    (puthash "M918" "Configure direct-connect display" hash)
    (puthash "M918" "Set TMC2130 PWM amplitude gradient (pwm_grad)" hash)
    (puthash "M928" "Start SD logging" hash)
    (puthash "M929" "Start/stop event logging to SD card" hash)
    (puthash "M950" "Create heater, fan or GPIO/servo device" hash)
    (puthash "M951" "Set height following mode parameters" hash)
    (puthash "M952" "Set CAN expansion board address and/or normal data rate" hash)
    (puthash "M953" "Set CAN-FD bus fast data rate" hash)
    (puthash "M995" "Calibrate Touch Screen" hash)
    (puthash "M997" "Perform in-application firmware update" hash)
    (puthash "M998" "Request resend of line" hash)
    (puthash "M999" "Restart after being stopped by error" hash)
    (puthash "D-1" "Endless Loop" hash)
    (puthash "D0" "Reset" hash)
    (puthash "D1" "Clear EEPROM and RESET" hash)
    (puthash "D2" "Read/Write RAM" hash)
    (puthash "D3" "Read/Write EEPROM" hash)
    (puthash "D4" "Read/Write PIN" hash)
    (puthash "D5" "Read/Write FLASH" hash)
    (puthash "D6" "Read/Write external FLASH" hash)
    (puthash "D7" "Read/Write Bootloader" hash)
    (puthash "D8" "Read/Write PINDA" hash)
    (puthash "D9" "Read/Write ADC" hash)
    (puthash "D10" "Set XYZ calibration = OK" hash)
    (puthash "D12" "Time" hash)
    (puthash "D80" "Bed check" hash)
    (puthash "D81" "Bed analysis" hash)
    (puthash "D106" "Print measured fan speed for different pwm values" hash)
    (puthash "D2130" "Trinamic stepper controller" hash)
    (puthash "D9125" "PAT9125 filament sensor" hash)
    hash))

;;; gcode-mode-doc.el ends here
